<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Tower Large 9L 3-Tier Steamer',
                'price' => '45',
                'image' => 'images/products/1.jpg',
                'category_id' => 1,
                'brand_id' => 3,
                'power_output_id' => 1,
                'color_id' => 1,
                'capacity_id' => 1,
            ],
            [
                'name' => 'Russell Hobbs 3-Tier Food Steamer',
                'price' => '489',
                'image' => 'images/products/2.jpg',
                'category_id' => 1,
                'brand_id' => 1,
                'power_output_id' => 2,
                'color_id' => 10,
                'capacity_id' => 2,
            ],
            [
                'name' => 'Salter EK2726 7.5L Healthy Cooking 3-Tier Food Rice Meat ',
                'price' => '215',
                'image' => 'images/products/3.jpg',
                'category_id' => 1,
                'brand_id' => 1,
                'power_output_id' => 3,
                'color_id' => 2,
                'capacity_id' => 3,
            ],
            [
                'name' => 'Russell Hobbs 14453 3-Tier Steamer - Stainless Steel',
                'price' => '345',
                'image' => 'images/products/4.jpg',
                'category_id' => 1,
                'brand_id' => 7,
                'power_output_id' => 4,
                'color_id' => 3,
                'capacity_id' => 4,
            ],
            [
                'name' => 'Geepas 0.6L 350W Rice Cooker with Steamer - White',
                'price' => '455',
                'image' => 'images/products/5.jpg',
                'category_id' => 1,
                'brand_id' => 8,
                'power_output_id' => 5,
                'color_id' => 4,
                'capacity_id' => 5,
            ],
            [
                'name' => 'Geepas 1.8L 700W Rice Cooker with Steamer - White',
                'price' => '675',
                'image' => 'images/products/6.jpg',
                'category_id' => 1,
                'brand_id' => 5,
                'power_output_id' => 6,
                'color_id' => 5,
                'capacity_id' => 6,
            ],
            [
                'name' => 'Tower 9.5L 3-Tier Digital Steamer - Black',
                'price' => '785',
                'image' => 'images/products/7.jpg',
                'category_id' => 1,
                'brand_id' => 4,
                'power_output_id' => 7,
                'color_id' => 6,
                'capacity_id' => 7,
            ],
            [
                'name' => 'Geepas 12L 1000W Food Steamer - Black & Silver',
                'price' => '345',
                'image' => 'images/products/8.jpg',
                'category_id' => 1,
                'brand_id' => 3,
                'power_output_id' => 8,
                'color_id' => 7,
                'capacity_id' => 8,
            ],
            [
                'name' => 'Elgento 2-Tier Steam Cooker',
                'price' => '125',
                'image' => 'images/products/9.jpg',
                'category_id' => 1,
                'brand_id' => 1,
                'power_output_id' => 9,
                'color_id' => 8,
                'capacity_id' => 9,
            ],
            [
                'name' => 'Tower T21001 3-Tier Food Steamer',
                'price' => '675',
                'image' => 'images/products/10.jpg',
                'category_id' => 1,
                'brand_id' => 2,
                'power_output_id' => 10,
                'color_id' => 9,
                'capacity_id' => 10,
            ],









            [
                'name' => 'Swan SF17031BN 6.5L Slow Cooker Retro - Black',
                'price' => '345',
                'image' => 'images/products/11.jpg',
                'category_id' => 2,
                'brand_id' => 3,
                'power_output_id' => 1,
                'color_id' => 1,
                'capacity_id' => 1,
            ],
            [
                'name' => 'Daewoo 3.5L Slow Cooker - Stainless Steel',
                'price' => '149',
                'image' => 'images/products/12.jpg',
                'category_id' => 2,
                'brand_id' => 1,
                'power_output_id' => 2,
                'color_id' => 10,
                'capacity_id' => 2,
            ],
            [
                'name' => 'Salter EK2726 7.5L Healthy Cooking 3-Tier Food Rice Meat ',
                'price' => '215',
                'image' => 'images/products/13.jpg',
                'category_id' => 2,
                'brand_id' => 1,
                'power_output_id' => 3,
                'color_id' => 2,
                'capacity_id' => 3,
            ],
            [
                'name' => 'Tefal 8in1 Cooker - 2L',
                'price' => '495',
                'image' => 'images/products/14.jpg',
                'category_id' => 2,
                'brand_id' => 7,
                'power_output_id' => 4,
                'color_id' => 3,
                'capacity_id' => 4,
            ],
            [
                'name' => 'Tower T16019BL 6.5L Stainless Steel Slow Cooker - Black',
                'price' => '455',
                'image' => 'images/products/15.jpg',
                'category_id' => 2,
                'brand_id' => 8,
                'power_output_id' => 5,
                'color_id' => 4,
                'capacity_id' => 5,
            ],
            [
                'name' => 'Morphy Richards Sear and Stew Slow Cooker - Red',
                'price' => '495',
                'image' => 'images/products/16.jpg',
                'category_id' => 2,
                'brand_id' => 5,
                'power_output_id' => 6,
                'color_id' => 5,
                'capacity_id' => 6,
            ],
            [
                'name' => 'Swan Stainless Steel Slow Cooker',
                'price' => '185',
                'image' => 'images/products/17.jpg',
                'category_id' => 2,
                'brand_id' => 4,
                'power_output_id' => 7,
                'color_id' => 6,
                'capacity_id' => 7,
            ],
            [
                'name' => 'Breville 1.5L Slow Cooker',
                'price' => '345',
                'image' => 'images/products/18.jpg',
                'category_id' => 2,
                'brand_id' => 3,
                'power_output_id' => 8,
                'color_id' => 7,
                'capacity_id' => 8,
            ],
            [
                'name' => 'Russell Hobbs 19750 Rice Cooker & Steamer - Stainless Steel',
                'price' => '125',
                'image' => 'images/products/19.jpg',
                'category_id' => 2,
                'brand_id' => 1,
                'power_output_id' => 9,
                'color_id' => 8,
                'capacity_id' => 9,
            ],
            [
                'name' => 'Daewoo 1.5L Manual Slow Cooker - Stainless Steel',
                'price' => '675',
                'image' => 'images/products/20.jpg',
                'category_id' => 2,
                'brand_id' => 2,
                'power_output_id' => 10,
                'color_id' => 9,
                'capacity_id' => 10,
            ],










            [
                'name' => 'Panasonic 20L 800W Solo Microwave Oven - Silver',
                'price' => '795',
                'image' => 'images/products/21.jpg',
                'category_id' => 3,
                'brand_id' => 3,
                'power_output_id' => 1,
                'color_id' => 1,
                'capacity_id' => 1,
            ],
            [
                'name' => 'Breville 20L Compact Manual Microwave - White',
                'price' => '349',
                'image' => 'images/products/22.jpg',
                'category_id' => 3,
                'brand_id' => 1,
                'power_output_id' => 2,
                'color_id' => 10,
                'capacity_id' => 2,
            ],
            [
                'name' => 'Sharp R372WM 25-Litre 900-Watt Microwave - White',
                'price' => '985',
                'image' => 'images/products/23.jpg',
                'category_id' => 3,
                'brand_id' => 1,
                'power_output_id' => 3,
                'color_id' => 2,
                'capacity_id' => 3,
            ],
            [
                'name' => 'Sharp YC-MS01U-B 20L 800W Solo Microwave - Black',
                'price' => '125',
                'image' => 'images/products/24.jpg',
                'category_id' => 3,
                'brand_id' => 7,
                'power_output_id' => 4,
                'color_id' => 3,
                'capacity_id' => 4,
            ],
            [
                'name' => 'Russell Hobbs 20L Manual Microwave - Silver',
                'price' => '345',
                'image' => 'images/products/25.jpg',
                'category_id' => 3,
                'brand_id' => 8,
                'power_output_id' => 5,
                'color_id' => 4,
                'capacity_id' => 5,
            ],
            [
                'name' => 'Russell Hobbs RHM2076S 20L Digital Microwave – Silver',
                'price' => '195',
                'image' => 'images/products/26.jpg',
                'category_id' => 3,
                'brand_id' => 5,
                'power_output_id' => 6,
                'color_id' => 5,
                'capacity_id' => 6,
            ],
            [
                'name' => 'Russell Hobbs RHM3003 30 Litre Microwave with Grill',
                'price' => '185',
                'image' => 'images/products/27.jpg',
                'category_id' => 3,
                'brand_id' => 4,
                'power_output_id' => 7,
                'color_id' => 6,
                'capacity_id' => 7,
            ],
            [
                'name' => 'Russell Hobbs Buckingham 17L Digital Microwave - Stainless',
                'price' => '345',
                'image' => 'images/products/28.jpg',
                'category_id' => 3,
                'brand_id' => 3,
                'power_output_id' => 8,
                'color_id' => 7,
                'capacity_id' => 8,
            ],
            [
                'name' => 'Swan Nordic Digital Microwave - White',
                'price' => '125',
                'image' => 'images/products/29.jpg',
                'category_id' => 3,
                'brand_id' => 1,
                'power_output_id' => 9,
                'color_id' => 8,
                'capacity_id' => 9,
            ],
            [
                'name' => 'Tower T24021W 800W 20L Digital Microwave - White',
                'price' => '675',
                'image' => 'images/products/30.jpg',
                'category_id' => 3,
                'brand_id' => 2,
                'power_output_id' => 10,
                'color_id' => 9,
                'capacity_id' => 10,
            ],





            [
                'name' => 'Salter XL Sandwich Maker',
                'price' => '795',
                'image' => 'images/products/31.jpg',
                'category_id' => 4,
                'brand_id' => 3,
                'power_output_id' => 1,
                'color_id' => 1,
                'capacity_id' => 1,
            ],
            [
                'name' => 'Salter 3-in-1 Deep Fill Sandwich and Waffle Maker',
                'price' => '349',
                'image' => 'images/products/32.jpg',
                'category_id' => 4,
                'brand_id' => 1,
                'power_output_id' => 2,
                'color_id' => 10,
                'capacity_id' => 2,
            ],
            [
                'name' => 'Tower Stainless Steel 750W Mini Panini Press',
                'price' => '985',
                'image' => 'images/products/33.jpg',
                'category_id' => 4,
                'brand_id' => 1,
                'power_output_id' => 3,
                'color_id' => 2,
                'capacity_id' => 3,
            ],
            [
                'name' => 'Salter Marble Ceramic 180 Low Fat Health Grill',
                'price' => '125',
                'image' => 'images/products/34.jpg',
                'category_id' => 4,
                'brand_id' => 7,
                'power_output_id' => 4,
                'color_id' => 3,
                'capacity_id' => 4,
            ],
            [
                'name' => 'George Foreman Compact 2-Portion Health Grill',
                'price' => '345',
                'image' => 'images/products/35.jpg',
                'category_id' => 4,
                'brand_id' => 8,
                'power_output_id' => 5,
                'color_id' => 4,
                'capacity_id' => 5,
            ],
            [
                'name' => 'Salter EK2384 Marble Collection 2-in-1 Ceramic Fold-Out',
                'price' => '195',
                'image' => 'images/products/36.jpg',
                'category_id' => 4,
                'brand_id' => 5,
                'power_output_id' => 6,
                'color_id' => 5,
                'capacity_id' => 6,
            ],
            [
                'name' => 'Russell Hobbs 3-in-1 Panini, Grill & Griddle',
                'price' => '185',
                'image' => 'images/products/37.jpg',
                'category_id' => 4,
                'brand_id' => 4,
                'power_output_id' => 7,
                'color_id' => 6,
                'capacity_id' => 7,
            ],
            [
                'name' => 'George Foreman 23450 10-Portion Entertaining Grill ',
                'price' => '345',
                'image' => 'images/products/38.jpg',
                'category_id' => 4,
                'brand_id' => 3,
                'power_output_id' => 8,
                'color_id' => 7,
                'capacity_id' => 8,
            ],
            [
                'name' => 'Salter EK2716 Omelette Maker',
                'price' => '125',
                'image' => 'images/products/39.jpg',
                'category_id' => 4,
                'brand_id' => 1,
                'power_output_id' => 9,
                'color_id' => 8,
                'capacity_id' => 9,
            ],
            [
                'name' => 'George Foreman Family 25040 5 Portion Steel Grill - Red',
                'price' => '675',
                'image' => 'images/products/40.jpg',
                'category_id' => 4,
                'brand_id' => 2,
                'power_output_id' => 10,
                'color_id' => 9,
                'capacity_id' => 10,
            ],








            [
                'name' => 'Geepas 35L Mini Oven & Grill with Double Hotplate - Black',
                'price' => '744',
                'image' => 'images/products/41.jpg',
                'category_id' => 5,
                'brand_id' => 3,
                'power_output_id' => 1,
                'color_id' => 1,
                'capacity_id' => 1,
            ],
            [
                'name' => 'Kalorik KitchenOriginals TKG MK 1002',
                'price' => '311',
                'image' => 'images/products/42.jpg',
                'category_id' => 5,
                'brand_id' => 1,
                'power_output_id' => 2,
                'color_id' => 10,
                'capacity_id' => 2,
            ],
            [
                'name' => 'Igenix 45L White Electric Mini Oven and Grill with Double Hot ',
                'price' => '185',
                'image' => 'images/products/43.jpg',
                'category_id' => 5,
                'brand_id' => 1,
                'power_output_id' => 3,
                'color_id' => 2,
                'capacity_id' => 3,
            ],
            [
                'name' => 'Igenix 30L Mini Oven with Double Hotplates',
                'price' => '895',
                'image' => 'images/products/44.jpg',
                'category_id' => 5,
                'brand_id' => 7,
                'power_output_id' => 4,
                'color_id' => 3,
                'capacity_id' => 4,
            ],
            [
                'name' => 'Russell Hobbs 22780 1920W 30L Mini Electric Oven with Twin',
                'price' => '345',
                'image' => 'images/products/45.jpg',
                'category_id' => 5,
                'brand_id' => 8,
                'power_output_id' => 5,
                'color_id' => 4,
                'capacity_id' => 5,
            ],
            [
                'name' => 'Galanz MOUK001B 30L 1500W Mini Convection Oven',
                'price' => '235',
                'image' => 'images/products/46.jpg',
                'category_id' => 5,
                'brand_id' => 5,
                'power_output_id' => 6,
                'color_id' => 5,
                'capacity_id' => 6,
            ],
            [
                'name' => 'Russell Hobbs Mini Electric Hob',
                'price' => '235',
                'image' => 'images/products/47.jpg',
                'category_id' => 5,
                'brand_id' => 4,
                'power_output_id' => 7,
                'color_id' => 6,
                'capacity_id' => 7,
            ],
            [
                'name' => 'Swan Single Boiling Ring',
                'price' => '564',
                'image' => 'images/products/48.jpg',
                'category_id' => 5,
                'brand_id' => 3,
                'power_output_id' => 8,
                'color_id' => 7,
                'capacity_id' => 8,
            ],
            [
                'name' => 'Elgento Double Boiling Ring',
                'price' => '145',
                'image' => 'images/products/49.jpg',
                'category_id' => 5,
                'brand_id' => 1,
                'power_output_id' => 9,
                'color_id' => 8,
                'capacity_id' => 9,
            ],
            [
                'name' => 'Severin Induction Hob - Black',
                'price' => '345',
                'image' => 'images/products/50.jpg',
                'category_id' => 5,
                'brand_id' => 2,
                'power_output_id' => 10,
                'color_id' => 9,
                'capacity_id' => 10,
            ],





            [
                'name' => 'Geepas 35L Mini Oven & Grill with Double Hotplate - Black',
                'price' => '744',
                'image' => 'images/products/51.jpg',
                'category_id' => 6,
                'brand_id' => 3,
                'power_output_id' => 1,
                'color_id' => 1,
                'capacity_id' => 1,
            ],
            [
                'name' => 'Kalorik KitchenOriginals TKG MK 1002',
                'price' => '311',
                'image' => 'images/products/52.jpg',
                'category_id' => 6,
                'brand_id' => 1,
                'power_output_id' => 2,
                'color_id' => 10,
                'capacity_id' => 2,
            ],
            [
                'name' => 'Igenix 45L White Electric Mini Oven and Grill with Double Hot ',
                'price' => '185',
                'image' => 'images/products/53.jpg',
                'category_id' => 6,
                'brand_id' => 1,
                'power_output_id' => 3,
                'color_id' => 2,
                'capacity_id' => 3,
            ],
            [
                'name' => 'Igenix 30L Mini Oven with Double Hotplates',
                'price' => '895',
                'image' => 'images/products/54.jpg',
                'category_id' => 6,
                'brand_id' => 7,
                'power_output_id' => 4,
                'color_id' => 3,
                'capacity_id' => 4,
            ],
            [
                'name' => 'Russell Hobbs 22780 1920W 30L Mini Electric Oven with Twin',
                'price' => '345',
                'image' => 'images/products/55.jpg',
                'category_id' => 6,
                'brand_id' => 8,
                'power_output_id' => 5,
                'color_id' => 4,
                'capacity_id' => 5,
            ],
            [
                'name' => 'Galanz MOUK001B 30L 1500W Mini Convection Oven',
                'price' => '235',
                'image' => 'images/products/56.jpg',
                'category_id' => 6,
                'brand_id' => 5,
                'power_output_id' => 6,
                'color_id' => 5,
                'capacity_id' => 6,
            ],
            [
                'name' => 'Russell Hobbs Mini Electric Hob',
                'price' => '235',
                'image' => 'images/products/57.jpg',
                'category_id' => 6,
                'brand_id' => 4,
                'power_output_id' => 7,
                'color_id' => 6,
                'capacity_id' => 7,
            ],
            [
                'name' => 'Swan Single Boiling Ring',
                'price' => '564',
                'image' => 'images/products/58.jpg',
                'category_id' => 6,
                'brand_id' => 3,
                'power_output_id' => 8,
                'color_id' => 7,
                'capacity_id' => 8,
            ],
            [
                'name' => 'Elgento Double Boiling Ring',
                'price' => '145',
                'image' => 'images/products/59.jpg',
                'category_id' => 6,
                'brand_id' => 1,
                'power_output_id' => 9,
                'color_id' => 8,
                'capacity_id' => 9,
            ],
            [
                'name' => 'Severin Induction Hob - Black',
                'price' => '345',
                'image' => 'images/products/60.jpg',
                'category_id' => 6,
                'brand_id' => 2,
                'power_output_id' => 10,
                'color_id' => 9,
                'capacity_id' => 10,
            ],






        ]);
    }
}
